config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#index'

  resources :users
  resources :catalogs
  resources :templates
  resources :semesters

  resources :courses do
    collection { post :do_import }
  end

  resources :requirements, only: [:do_import] do
    collection { post :do_import }
  end

  get '/predict' => 'predict#index'
  post '/predict/run' => 'predict#run'

  get 'manage' => 'home#manage'
  get 'help' => 'home#help'

  get 'import',               to: "importer#index"
  get 'import/courses',       to: 'importer#courses'
  get 'import/requirements',  to: 'importer#reqs'

  get 'courses_by_semester/:id' => 'courses#by_semester', as: 'courses_by_semester'
  get 'all_courses' => 'courses#all_courses'

end

app/views/templates/edit.html.haml
%h1 Editing template

= render 'form'

= link_to 'Show', @template
\|
= link_to 'Back', templates_path

app/views/templates/index.html.haml
.col-md-12
  .panel.panel-info
    .panel-heading.clearfix
      %h4.panel-title.pull-left
        Course Templates
      .pull-right
        = link_to new_template_path, class: 'btn btn-primary btn-xs' do
          %i.fa.fa-plus
          New Course Template

    .panel-body
      #catalogs
        = render 'templates/partials/table'

    .panel-footer
      = link_to 'Dashboard', root_path, class: 'btn btn-success'

app/views/templates/new.html.haml
= render 'templates/partials/form'

app/views/templates/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_template_path(@template)
\|
= link_to 'Back', templates_path