config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#index'

  resources :users
  resources :catalogs
  resources :templates
  resources :semesters

  resources :courses do
    collection { post :do_import }
  end

  resources :requirements, only: [:do_import] do
    collection { post :do_import }
  end

  get '/predict' => 'predict#index'
  post '/predict/run' => 'predict#run'

  get 'manage' => 'home#manage'
  get 'help' => 'home#help'

  get 'import',               to: "importer#index"
  get 'import/courses',       to: 'importer#courses'
  get 'import/requirements',  to: 'importer#reqs'

  get 'courses_by_semester/:id' => 'courses#by_semester', as: 'courses_by_semester'
  get 'all_courses' => 'courses#all_courses'

end

app/views/partials/_badger.html.haml
.col-md-12
  .badger-left{"data-badger" => "Badger default (left)"}
    Block with badger 1
  .offer.offer-default
    .shape
      .shape-text
        top
    .offer-content
      %h3.lead
        A default offer
      %p
        And a little description.
        %br/
        and so one
      %button.btn.btn-primary.btn-lg{"data-target" => "#myModal", "data-toggle" => "modal"}
        Launch demo modal

#myModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", role: "dialog", tabindex: "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"} ×
        %h4#myModalLabel.modal-title Modal title
      .modal-body
        \...
      .modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal", type: "button"} Close
        %button.btn.btn-primary{type: "button"} Save changes

app/views/partials/_fileinput.html.haml
.col-md-12
  %form{enctype: "multipart/form-data"}
    .form-group
      %input#file-1.file{"data-preview-file-type" => "any", multiple: "true", type: "file"}/
    .form-group
      %input#file-2.file{readonly: "true", type: "file"}/
    .form-group
      %input#file-3{multiple: "true", type: "file"}/
    .form-group
      %button.btn.btn-primary Submit
      %button.btn.btn-default{type: "reset"} Reset

app/views/partials/_flash.html.haml
.flash-div.col-md-12
  - flash.each do |key, value|
    .alert{ class: flash_class(key) }
      %button.close{ :data => { :dismiss => "alert" } } x
      %strong
        = value


:javascript
  $(function() {
    $('.alert').hide().delay(200).fadeIn(500).delay(2000).fadeOut(500)
  });

app/views/partials/_sitenav.html.haml
%nav.navbar.navbar-inverse.navbar-fixed-top.navbar-default{role: "navigation"}
  .container-fluid
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %button.navbar-toggle{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", type: "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{href: "/"} CEPS
    / Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li
          = link_to root_path do
            %i.fa.fa-home
            Home
        %li
          = link_to predict_path do
            %i.fa.fa-bullseye
            Predict

        %li.dropdown
          %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
            %i.fa.fa-database
            Manage
            %b.caret
          %ul.dropdown-menu
            %li
              = link_to courses_path do
                %i.fa.fa-book
                %nbsp Courses

            %li
              = link_to semesters_path do
                %i.fa.fa-calendar-o
                Semesters
            %li
              = link_to catalogs_path do
                %i.fa.fa-calendar
                Catalogs

            %li.divider
            %li
              = link_to users_path do
                %i.fa.fa-user
                Users

            %li.divider
            %li
              = link_to import_path do
                %i.fa.fa-upload
                Import Data

      %ul.nav.navbar-nav.navbar-right
        - if current_user
          %li.dropdown
            %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
              Welcome #{current_user.first_name}
              %b.caret
            %ul.dropdown-menu
              %li= link_to "User Profile", current_user
              %li= link_to "Log out", destroy_user_session_path, :method => :delete
        - else
          %li= link_to 'Sign In', new_user_session_path
    //.navbar-collapse
  //.container-fluid