config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#index'

  resources :users
  resources :catalogs
  resources :templates
  resources :semesters

  resources :courses do
    collection { post :do_import }
  end

  resources :requirements, only: [:do_import] do
    collection { post :do_import }
  end

  get '/predict' => 'predict#index'
  post '/predict/run' => 'predict#run'

  get 'manage' => 'home#manage'
  get 'help' => 'home#help'

  get 'import',               to: "importer#index"
  get 'import/courses',       to: 'importer#courses'
  get 'import/requirements',  to: 'importer#reqs'

  get 'courses_by_semester/:id' => 'courses#by_semester', as: 'courses_by_semester'
  get 'all_courses' => 'courses#all_courses'

end

app/controllers/importer_controller.rb
class ImporterController < ApplicationController
  before_action :authenticate_user!
end

app/helpers/importer_helper.rb
module ImporterHelper
end

app/views/importer/courses.html.haml
= form_tag(do_import_courses_path, html: { role: "form" }, multipart: true) do
  .col-md-12
    .panel.panel-info
      .panel-heading
        %h4.panel-title Import Course Data

      .panel-body
        .row
          .col-md-6
            .bs-example
              %p(style="overflow: none")
                = image_tag('spreadsheet1.png', class: "img-responsive center-block")
              %p
                The above image depicts an example data import file.  Be sure to setup your import spreadsheet in a
                similar fashion using the first row of the spreadsheet as a header and then having the following
                columns (in order):

              .bs-callout.bs-callout-warning
                %h4 Column Headings
                %table.table.table-condensed
                  %tr
                    %td.strong crn
                    %td Course registration number
                  %tr
                    %td.strong number
                    %td Course catalog number
                  %tr
                    %td.strong credits
                    %td Number of credits
                  %tr
                    %td.strong title
                    %td Course catalog title
                  %tr
                    %td.strong enr_cap
                    %td Enrollment capacity
                  %tr
                    %td.strong enr_act
                    %td Actual enrollment
                  %tr
                    %td.strong wait_cap
                    %td Waitlist capacity
                  %tr
                    %td.strong wait_act
                    %td Actual enrollment
                  %tr
                    %td.strong passed
                    %td # of students passing

          .col-md-6
            %h4(style="border-bottom: solid 1px #dcdcdc")
              Browse for Import File

            .bs-callout.bs-callout-info
              %h4 Regarding Importing Course Data
              Import file must be a Microsoft Excel '97 (.xls) or Microsoft Excel '07 (.xlsx) format.  Click the
              <strong><em>Browse</em></strong> button to select your import file.  When you have selected your import file,
              click the <strong><em>Import Data</em></strong> button below.

            .row
              .col-md-6
                .form-group
                  %label.form-label Semester
                  = collection_select :course, :semester_id, Semester.all, :id, :full_title, { include_blank: '' }, class: "form-control"

              .col-md-6
                .form-group
                  %label.form-label Worksheet #

                  = text_field :worksheet, :worksheet_id, class: 'form-control', value: '0'

              .col-md-12
                = file_field_tag :file, class: 'file'

              .col-md-12(style="margin-top: 20px")
                = submit_tag 'Import Data', class: 'btn btn-info btn-lg center-block'

      .panel-footer
        = link_to 'Import Data Home', import_path, class: 'btn btn-success'

:coffee
  $(".file").fileinput({'showUpload':false, 'previewFileType':'any'});

app/views/importer/index.html.haml
= stylesheet_link_tag 'home'

.jumbotron
  .container
    .col-md-12
      .text-center
        %i.fa.fa-cubes.fa-5x
        %h1.raleway
          <span class="letter">I</span><span class="word">mport<span>
          <span class="letter">C</span><span class="word">ourse</span>
          <span class="letter">D</span><span class="word">ata</span>

.container
  .col-md-12
    .col-md-4
      = link_to import_courses_path, class: 'btn btn-default btn-lg btn-block' do
        %i.fa.fa-upload.fa-5x
        %h3.raleway Course Data

    .col-md-4
      .text-center
        = link_to import_requirements_path, class: 'btn btn-default btn-lg btn-block' do
          %i.fa.fa-upload.fa-5x
          %h3.raleway Course Requirements

    .col-md-4
      .text-center
        = link_to help_path, class: 'btn btn-default btn-lg btn-block' do
          %i.fa.fa-question-circle.fa-5x
          %h3.raleway Get Help

app/views/importer/reqs.html.haml
= form_tag(do_import_requirements_path, html: { role: "form" }, multipart: true) do
  .col-md-12
    .panel.panel-warning
      .panel-heading
        %h4.panel-title Import Course Requirements

      .panel-body
        .row
          .col-md-6
            .bs-example
              %p(style="overflow: none")
                = image_tag('spreadsheet2.png', class: "img-responsive center-block")
              %p
                The above image depicts an example data import file.  Be sure to setup your import spreadsheet in a
                similar fashion using the first row of the spreadsheet as a header and then having the following
                columns (in order):

              .bs-callout.bs-callout-warning
                %h4 Column Headings
                %table.table.table-condensed
                  %tr
                    %td.strong course
                    %td Course registration number
                  %tr
                    %td.strong coreq1
                    %td 1st Co-req Course Number
                  %tr
                    %td.strong condition1
                    %td AND/OR condition
                  %tr
                    %td.strong coreq2
                    %td 2nd Co-req Course Number
                  %tr
                    %td.strong prereq1
                    %td 1st Pre-requisite Course Number
                  %tr
                    %td.strong condition2
                    %td AND/OR condition
                  %tr
                    %td.strong prereq2
                    %td 2nd Pre-requisite Course Number
                  %tr
                    %td.strong prereq3
                    %td 3rd Pre-requisite Course Number
                  %tr
                    %td.strong condition3
                    %td AND/OR condition
                  %tr
                    %td.strong prereq4
                    %td 4th Pre-requisite Course Number

          .col-md-6
            %h4(style="border-bottom: solid 1px #dcdcdc")
              Browse for Import File

            .bs-callout.bs-callout-info
              %h4 Regarding Importing Requirements
              Import file must be a Microsoft Excel '97 (.xls) or Microsoft Excel '07 (.xlsx) format.  Click the
              <strong><em>Browse</em></strong> button to select your import file.  When you have selected your import file,
              click the <strong><em>Import Data</em></strong> button below.

            .row
              .col-md-6
                .form-group
                  %label.form-label Semester
                  = collection_select :course, :semester_id, Semester.all, :id, :full_title, { include_blank: '' }, class: "form-control"

              .col-md-6
                .form-group
                  %label.form-label Worksheet #
                  = text_field :worksheet, :worksheet_id, class: 'form-control', value: '0'

              .col-md-12
                = file_field_tag :file, class: 'file'

              .col-md-12(style="margin-top: 20px")
                = submit_tag 'Import Data', class: 'btn btn-info btn-lg center-block'

      .panel-footer
        = link_to 'Import Data Home', import_path, class: 'btn btn-success'

:coffee
  $(".file").fileinput({'showUpload':false, 'previewFileType':'any'});