config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#index'

  resources :users
  resources :catalogs
  resources :templates
  resources :semesters

  resources :courses do
    collection { post :do_import }
  end

  resources :requirements, only: [:do_import] do
    collection { post :do_import }
  end

  get '/predict' => 'predict#index'
  post '/predict/run' => 'predict#run'

  get 'manage' => 'home#manage'
  get 'help' => 'home#help'

  get 'import',               to: "importer#index"
  get 'import/courses',       to: 'importer#courses'
  get 'import/requirements',  to: 'importer#reqs'

  get 'courses_by_semester/:id' => 'courses#by_semester', as: 'courses_by_semester'
  get 'all_courses' => 'courses#all_courses'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def manage
  end

  def help
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/help.html.haml
= stylesheet_link_tag 'home'

.jumbotron
  .container
    .col-md-12
      .text-center
        %i.fa.fa-cubes.fa-5x
        %h1.raleway
          <span class="letter">H</span><span class="word">elp<span>
          <span class="letter">U</span><span class="word">sing</span>
          <span class="letter">P</span><span class="word">rediction</span>
          <span class="letter">S</span><span class="word">ystem</span>

.container
  .col-md-12
    .col-md-4
      .text-center
        = link_to manage_path, class: 'btn btn-default btn-lg btn-block' do
          %i.fa.fa-database.fa-5x
          %h3.raleway
            Managing Data

    .col-md-4
      .text-center
        = link_to predict_path, class: 'btn btn-default btn-lg btn-block' do
          %i.fa.fa-bullseye.fa-5x
          %h3.raleway
            Running Predictions

    .col-md-4
      .text-center
        = link_to predict_path, class: 'btn btn-default btn-lg btn-block' do
          %i.fa.fa-bullseye.fa-5x
          %h3.raleway
            Administering System

app/views/home/index.html.haml
= stylesheet_link_tag 'home'

.jumbotron
  .container
    .col-md-12
      .text-center
        %i.fa.fa-cubes.fa-5x
        %h1.raleway
          <span class="letter">C</span><span class="word">ourse<span>
          <span class="letter">E</span><span class="word">nrollment</span>
          <span class="letter">P</span><span class="word">rediction</span>
          <span class="letter">S</span><span class="word">ystem</span>

.container
  .col-md-12
    .col-md-4
      .text-center
        = link_to manage_path, class: 'btn btn-default btn-lg btn-block' do
          %i.fa.fa-database.fa-5x
          %h3.raleway Manage Data

    .col-md-4
      .text-center
        = link_to predict_path, class: 'btn btn-default btn-lg btn-block' do
          %i.fa.fa-bullseye.fa-5x
          %h3.raleway Predict Enrollment

    .col-md-4
      .text-center
        = link_to help_path, class: 'btn btn-default btn-lg btn-block' do
          %i.fa.fa-question-circle.fa-5x
          %h3.raleway Get Help

app/views/home/manage.html.haml
= stylesheet_link_tag 'home'

.jumbotron
  .container
    .col-md-12
      .text-center
        %i.fa.fa-cubes.fa-5x
        %h1.raleway
          <span class="letter">M</span><span class="word">anage</span>
          <span class="letter">P</span><span class="word">rediction</span>
          <span class="letter">D</span><span class="word">ata</span>

.container
  .row
    .col-md-12
      .col-md-4
        .text-center
          = link_to courses_path, class: 'btn btn-default btn-lg btn-block' do
            %i.fa.fa-cube.fa-5x
            %h3.raleway Manage Courses

      .col-md-4
        .text-center
          = link_to semesters_path, class: 'btn btn-default btn-lg btn-block' do
            %i.fa.fa-cubes.fa-5x
            %h3.raleway Manage Semesters

      .col-md-4
        .text-center
          = link_to catalogs_path, class: 'btn btn-default btn-lg btn-block' do
            %i.fa.fa-calendar.fa-5x
            %h3.raleway Manage Catalogs

.container.vert-offset-30
  .row
    .col-md-12
      .col-md-4.col-md-offset-4
        .text-center
          = link_to import_path, class: 'btn btn-default btn-lg btn-block' do
            %i.fa.fa-upload.fa-5x
            %h3.raleway Import Data